/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 SP2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "PWM_hojre.h"
#include "Clock_1.h"
#include "PWM_RIGHT.h"
#include "PWM_RIGHT_aliases.h"
#include "ADC.h"
#include "Pin.h"
#include "Pin_aliases.h"
#include "speedPin.h"
#include "speedPin_aliases.h"
#include "PWM_venstre.h"
#include "PWM_left.h"
#include "PWM_left_aliases.h"
#include "Pin_1.h"
#include "Pin_1_aliases.h"
#include "Echo.h"
#include "Echo_aliases.h"
#include "Trig.h"
#include "Trig_aliases.h"
#include "LED.h"
#include "LED_aliases.h"
#include "Timer.h"
#include "Clock.h"
#include "ISR.h"
#include "UART_print.h"
#include "UART_print_SPI_UART.h"
#include "UART_print_PINS.h"
#include "UART_print_SPI_UART_PVT.h"
#include "UART_print_PVT.h"
#include "UART_print_BOOT.h"
#include "I2C_1.h"
#include "I2C_1_I2C.h"
#include "I2C_1_PINS.h"
#include "I2C_1_I2C_PVT.h"
#include "I2C_1_PVT.h"
#include "I2C_1_BOOT.h"
#include "ADC_IRQ.h"
#include "ADC_intClock.h"
#include "UART_print_SCBCLK.h"
#include "UART_print_tx.h"
#include "UART_print_tx_aliases.h"
#include "UART_print_rx.h"
#include "UART_print_rx_aliases.h"
#include "I2C_1_SCBCLK.h"
#include "I2C_1_sda.h"
#include "I2C_1_sda_aliases.h"
#include "I2C_1_scl.h"
#include "I2C_1_scl_aliases.h"
#include "I2C_1_SCB_IRQ.h"
#include "core_cm0_psoc4.h"
#include "core_cm0.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"
#include "CyLFClk.h"

/*[]*/

